theme: minima
title: A New Start
author: Dolly-Chan
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  It seems difficult to do something, so you flinched. But if 
  you try, you will find ...
 
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
